export const ADD_NUMBER = "ADD_NUMBER";
export const REMOVE_NUMBER = "REMOVE_NUMBER";
export const UPDATE_RECIPES = "UPDATE_RECIPES";
export const SELECT_RECIPE = "SELECT_RECIPE";
export const ADD_SHOPPING_LIST_ITEM = "ADD_SHOPPING_LIST_ITEM";
export const REMOVE_SHOPPING_LIST_ITEM = "REMOVE_SHOPPING_LIST_ITEM";
export const ARCHIVE_SHOPPING_LIST_ITEM = "ARCHIVE_SHOPPING_LIST_ITEM";